version: '3.7'

services:
  postgresql:
    container_name: siosa_postgres
    image: siosa_postgres
    build:
      context: ./database
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
