import css from './styles.css';

import Dropdown from '../Dropdown/Dropdown';

const ascendancies = [
  { value: 'Ascendant' },
  { value: 'Slayer' },
  { value: 'Gladiator' },
  { value: 'Champion' },
  { value: 'Assassin' },
  { value: 'Saboteur' },
  { value: 'Trickster' },
  { value: 'Juggernaut' },
  { value: 'Berserker' },
  { value: 'Chieftain' },
  { value: 'Necromancer' },
  { value: 'Elementalist' },
  { value: 'Occultist' },
  { value: 'Deadeye' },
  { value: 'Raider' },
  { value: 'Pathfinder' },
  { value: 'Inquisitor' },
  { value: 'Hierophant' },
  { value: 'Guardian' },
];

const skills = [
  { value: 'Animate Weapon' },
  { value: 'Arctic Armour' },
  { value: 'Artillery Ballista' },
  { value: 'Barrage' },
  { value: 'Bear Trap' },
  { value: 'Blade Flurry' },
  { value: 'Blade Vortex' },
  { value: 'Bladefall' },
  { value: 'Blast Rain' },
  { value: 'Blink Arrow' },
  { value: 'Blood Rage' },
  { value: 'Burning Arrow' },
  { value: 'Caustic Arrow' },
  { value: 'Charged Dash' },
  { value: 'Cobra Lash' },
  { value: 'Cremation' },
  { value: 'Cyclone' },
  { value: 'Dash' },
  { value: 'Desecrate' },
  { value: 'Detonate Dead' },
  { value: 'Double Strike' },
  { value: 'Dual Strike' },
  { value: 'Elemental Hit' },
  { value: 'Ensnaring Arrow' },
  { value: 'Ethereal Knives' },
  { value: 'Explosive Arrow' },
  { value: 'Explosive Trap' },
  { value: 'Fire Trap' },
  { value: 'Flamethrower Trap' },
  { value: 'Flicker Strike' },
  { value: 'Frenzy' },
  { value: 'Frost Blades' },
  { value: 'Galvanic Arrow' },
  { value: 'Grace' },
  { value: 'Haste' },
  { value: 'Hatred' },
  { value: 'Herald of Agony' },
  { value: 'Herald of Ice' },
  { value: 'Ice Shot' },
  { value: 'Ice Trap' },
  { value: 'Lacerate' },
  { value: 'Lancing Steel' },
  { value: 'Lightning Arrow' },
  { value: 'Lightning Strike' },
  { value: 'Mirror Arrow' },
  { value: 'Pestilent Strike' },
  { value: 'Phase Run' },
  { value: 'Plague Bearer' },
  { value: "Poacher's Mark" },
  { value: 'Precision' },
  { value: 'Projectile Weakness' },
  { value: 'Puncture' },
  { value: 'Purity of Ice' },
  { value: 'Rain of Arrows' },
  { value: 'Reave' },
  { value: 'Riposte' },
  { value: 'Scourge Arrow' },
  { value: 'Seismic Trap' },
  { value: 'Shattering Steel' },
  { value: 'Shrapnel Ballista' },
  { value: 'Siege Ballista' },
  { value: 'Smoke Mine' },
  { value: 'Spectral Shield Throw' },
  { value: 'Spectral Throw' },
  { value: 'Split Arrow' },
  { value: 'Summon Ice Golem' },
  { value: 'Temporal Chains' },
  { value: 'Tornado Shot' },
  { value: 'Toxic Rain' },
  { value: 'Unearth' },
  { value: 'Venom Gyre' },
  { value: 'Viper Strike' },
  { value: 'Volatile Dead' },
  { value: 'Whirling Blades' },
  { value: 'Wild Strike' },
  { value: 'Withering Step' },
  { value: 'Skill gem' },
  { value: 'Abyssal Cry' },
  { value: 'Ancestral Protector' },
  { value: 'Ancestral Warchief' },
  { value: 'Anger' },
  { value: 'Animate Guardian' },
  { value: 'Berserk' },
  { value: 'Bladestorm' },
  { value: 'Blood and Sand' },
  { value: 'Chain Hook' },
  { value: 'Cleave' },
  { value: 'Consecrated Path' },
  { value: 'Decoy Totem' },
  { value: 'Determination' },
  { value: 'Devouring Totem' },
  { value: 'Dominating Blow' },
  { value: 'Dread Banner' },
  { value: 'Earthquake' },
  { value: 'Enduring Cry' },
  { value: 'Flesh and Stone' },
  { value: 'Glacial Hammer' },
  { value: 'Ground Slam' },
  { value: 'Heavy Strike' },
  { value: 'Herald of Ash' },
  { value: 'Herald of Purity' },
  { value: 'Holy Flame Totem' },
  { value: 'Ice Crash' },
  { value: 'Immortal Call' },
  { value: 'Infernal Blow' },
  { value: 'Leap Slam' },
  { value: 'Molten Shell' },
  { value: 'Molten Strike' },
  { value: 'Perforate' },
  { value: 'Pride' },
  { value: 'Punishment' },
  { value: 'Purity of Fire' },
  { value: 'Rallying Cry' },
  { value: 'Reckoning' },
  { value: 'Rejuvenation Totem' },
  { value: 'Searing Bond' },
  { value: 'Shield Charge' },
  { value: 'Shockwave Totem' },
  { value: 'Smite' },
  { value: 'Static Strike' },
  { value: 'Steelskin' },
  { value: 'Summon Flame Golem' },
  { value: 'Summon Stone Golem' },
  { value: 'Sunder' },
  { value: 'Sweep' },
  { value: 'Tectonic Slam' },
  { value: 'Vengeance' },
  { value: 'Vigilant Strike' },
  { value: 'Vitality' },
  { value: 'Vulnerability' },
  { value: 'War Banner' },
  { value: "Warlord's Mark" },
  { value: 'Skill gem' },
  { value: 'Arc' },
  { value: 'Arctic Breath' },
  { value: 'Armageddon Brand' },
  { value: "Assassin's Mark" },
  { value: 'Ball Lightning' },
  { value: 'Bane' },
  { value: 'Blight' },
  { value: 'Bodyswap' },
  { value: 'Bone Offering' },
  { value: 'Brand Recall' },
  { value: 'Clarity' },
  { value: 'Cold Snap' },
  { value: 'Conductivity' },
  { value: 'Contagion' },
  { value: 'Conversion Trap' },
  { value: 'Convocation' },
  { value: 'Dark Pact' },
  { value: 'Despair' },
  { value: 'Discharge' },
  { value: 'Discipline' },
  { value: 'Divine Ire' },
  { value: 'Elemental Weakness' },
  { value: 'Enfeeble' },
  { value: 'Essence Drain' },
  { value: 'Fireball' },
  { value: 'Firestorm' },
  { value: 'Flame Dash' },
  { value: 'Flame Surge' },
  { value: 'Flameblast' },
  { value: 'Flammability' },
  { value: 'Flesh Offering' },
  { value: 'Freezing Pulse' },
  { value: 'Frost Bomb' },
  { value: 'Frost Wall' },
  { value: 'Frostbite' },
  { value: 'Frostblink' },
  { value: 'Frostbolt' },
  { value: 'Glacial Cascade' },
  { value: 'Herald of Thunder' },
  { value: 'Ice Nova' },
  { value: 'Ice Spear' },
  { value: 'Icicle Mine' },
  { value: 'Incinerate' },
  { value: 'Kinetic Blast' },
  { value: 'Lightning Spire Trap' },
  { value: 'Lightning Tendrils' },
  { value: 'Lightning Trap' },
  { value: 'Lightning Warp' },
  { value: 'Magma Orb' },
  { value: 'Malevolence' },
  { value: 'Orb of Storms' },
  { value: 'Power Siphon' },
  { value: 'Purifying Flame' },
  { value: 'Purity of Elements' },
  { value: 'Purity of Lightning' },
  { value: 'Pyroclast Mine' },
  { value: 'Raise Spectre' },
  { value: 'Raise Zombie' },
  { value: 'Righteous Fire' },
  { value: 'Scorching Ray' },
  { value: 'Shock Nova' },
  { value: 'Siphoning Trap' },
  { value: 'Soulrend' },
  { value: 'Spark' },
  { value: 'Spirit Offering' },
  { value: 'Storm Brand' },
  { value: 'Storm Burst' },
  { value: 'Storm Call' },
  { value: 'Stormblast Mine' },
  { value: 'Summon Carrion Golem' },
  { value: 'Summon Chaos Golem' },
  { value: 'Summon Holy Relic' },
  { value: 'Summon Lightning Golem' },
  { value: 'Summon Raging Spirit' },
  { value: 'Summon Skeletons' },
  { value: 'Summon Skitterbots' },
  { value: 'Tempest Shield' },
  { value: 'Vortex' },
  { value: 'Wave of Conviction' },
  { value: 'Winter Orb' },
  { value: 'Wither' },
  { value: 'Wrath' },
  { value: 'Zealotry' },
  { value: 'Skill gem' },
  { value: 'Detonate Mines' },
  { value: 'Portal' },
];

export default () => {
  return (
    <div className={css.search}>
      <Dropdown options={ascendancies} placeholder='Ascendancy' />
      <Dropdown options={skills} placeholder='Skill gem' />
      <input placeholder='Items' disabled />
    </div>
  );
};
